name: Destroy Resources

on:
  workflow_dispatch: # Allows you to run the workflow manually
  schedule:
    - cron: '0 7 * * 1-5' # Runs at 7 AM UTC / 5 PM AEST, Monday to Friday

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZUREKEY }}

    - name: Destroy Resource Group
      run: |
        az group delete --name SecurityCopilot --yes --no-wait
